# .woodpecker.yml
steps:
  - name: build & copy
    image: node:18-alpine
    when:
      - branch: master
        event: push
    commands:
      - apk add --no-cache openssh-client
      - mkdir -p /root/.ssh/
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - npm install
      - npm run build
      - ssh "$REMOTE_HOST" 'rm -rf /mnt/nvme/www/equipment_tracker_frontend/*'
      - scp -r dist/* root@"$REMOTE_HOST":/mnt/nvme/www/equipment_tracker_frontend
    secrets: [SSH_KEY, REMOTE_HOST]
