pipeline:
  - name: build
    image: node:14
    commands:
      - npm install
      - npm run build
  - name: copy
    image: alpine
    environment:
      - SSH_KEY:
          from_secret: ssh_key
    commands:
      - apk add --no-cache openssh-client
      - echo "$SSH_KEY" | tr -d '\r' > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > /root/.ssh/config
      - scp -r dist/* username@10.0.10.4:/mnt/sda1/projects/equipment_tracker_frontend
